title: "Marek Cmero"
masthead_title: " "
email:
description: "Marek Cmero's blog and web site."
github_username: mcmero
repository: "mcmero/mcmero.github.io"
minimal_mistakes_skin: default
search: true
#comments:
#  provider: "staticman_v2"
#  staticman:
#    branch: "master"
#    endpoint: "https://mcmeroio.herokuapp.com/v2/entry/"
reCaptcha:
  siteKey: "6LfY_c4ZAAAAANLSqTDj9S3mYNcNIVSnGhYDeB_o"
  secret: "YzN6MJiVEmaZD5vAbJhRqdkaEb++YE3WdHFybNQpaHMAOhi32vBOJFatub9aaMao847TrVGnNMQKdZy17voC+2DOuUzKwsw9cVwMW0wbts5IAZxPKsQrMJ8CqlkvU/kFZY66XjyflyZGhMdxnQAWL91sWJ4TaLmUG0RbpNI/xP8s5EKe+LiApOpDdzwezzbu+5WJRYej0R27Gh1wHBuSjC/MHTs3S7kxCzZa/yJuQd11M++awRYf2k7HocRnpf+9qe5TCN5QRMgldim5LmRVKukMQztMx8KTR3PJRHhtLxQhv1ummEILKjzQKyavAc2/cgYrQBAbVXlIKmrc31j5ySqKxxD79h7f7Tqjpp8jh1B9Qz/ZKtARvTqRfdoZORKPNYw6it/VQZZR5EBLxE632Nk78bCS1RLyfqyH5k/fUIS1VkR2DZFSSzttC+zc7xCwRHkj9MRzV0ZhOit2/mNULZSA7anxhc9pImpoPbxOM1wJaM27xrJ82OzhpNi77hDCIwDr9jVm9tKtDA6aaENP5YHHCCmKaS7NPzqWZTD4LkY+amFZUl4BTp8yPvT844ptqlECfMndxz1CslxuPb69AVNMF4kSMZGj+RsT2LvxQxxCDP7hRh3/0MMks+7EJJn69j6JTMkG+PWmzSUJNaOF1yz4x8PfzER9DuWPIWm6m1M="

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Marek Cmero"
  avatar : "images/me.jpg"
  location : "Melbourne, Australia"
  bio    : "I'm a Senior Research Officer at [WEHI](https://www.wehi.edu.au/) working in the area of sequencing bioinformatics. I'm interested in improving research outcomes through software and novel computational methods."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:cmerom@unimelb.edu.au
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mcmero"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marek-cmero"
    - label: "Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=OQTfAgYAAAAJ"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0001-7783-5530"

footer:
  links:


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
